CLASS LHC_ZBS_R_DEMOLISTREPORT DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CUSTOM FOR MODIFY
        IMPORTING KEYS FOR ACTION ListReport~Custom,
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ListReport
        RESULT result.
ENDCLASS.

CLASS LHC_ZBS_R_DEMOLISTREPORT IMPLEMENTATION.
  METHOD CUSTOM.
  ENDMETHOD.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
